"""Convert labgen sim demos into yam_vr_teleop's demo format.

The lab records real demos with yam_vr_teleop (github.com/nhern026/yam_vr_teleop)
and trains from them via its own exporter (deployment/export_demos.py -> CSV or
LeRobot v2.1 for pi0.5). This writes sim demos -- teleoperated, or generated by
MimicGen -- in that SAME raw HDF5 layout, one file per demo, so the lab's
exporter turns real and sim data into one dataset format with no second code
path:

    python export_yam_vr.py demos/vial_gen.hdf5 out/yam_vr/          # this script
    cd $TELEOP        && .venv/bin/python -m deployment.export_demos \\
        ~/labgen/out/yam_vr/ --lerobot out/sim_dataset                  # theirs

DO NOT pass --fps above the sim's rate (20 Hz). Their exporter only resamples
DOWN; asked for more (e.g. --fps 30) it keeps every frame but labels the
dataset 30 fps -- measured: a 48 s, 20 Hz demo written as 960 frames "@ 30 Hz",
i.e. time-compressed 1.5x with no warning. Their own demos are 100 Hz so they
never hit it. Omit --fps (keeps 20 Hz) or pass --fps <= 20.

Mapping (per arm group /left, /right):
  joint_position / joint_velocity  measured arm joints (6)
  joint_target                     COMMANDED arm joints (6) -- the policy obs
                                   robot{i}_joint_target; demos recorded before
                                   that obs existed are refused, not guessed
  gripper_position / _command      opening in [0, 1], 1 = open, from the finger
                                   joint / its commanded target
  ee_position / ee_quaternion      labgen's grasp point (pad midpoint) in that
                                   arm's base frame, quaternion xyzw -- NOT i2rt's
                                   end-effector site; recorded for reference only

robot0 -> --robot0-hand (default left), robot1 -> the other. In the sim the
second arm's placement is a PLACEHOLDER; say so before mixing with real data.
Runs anywhere with numpy and h5py.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import h5py
import numpy as np

JAW_OPEN_Q = -0.0469          # labgen_tasks.bench_yam.JAW_OPEN_Q: finger joint when fully open


def quat_wxyz_to_R(q):
    w, x, y, z = q[..., 0], q[..., 1], q[..., 2], q[..., 3]
    return np.stack([
        np.stack([1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)], -1),
        np.stack([2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)], -1),
        np.stack([2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)], -1)], -2)


def convert(demo: h5py.Group, hz: float, hands: list[str], out: Path, meta: dict) -> None:
    obs = demo["obs"]
    n = demo["actions"].shape[0]
    with h5py.File(out, "w") as f:
        f.attrs["hz"] = hz
        f.attrs["arms"] = hands
        f.attrs["num_ticks"] = n
        f.attrs["duration_s"] = round(n / hz, 3)
        f.attrs["source"] = "labgen sim"
        for k, v in meta.items():
            f.attrs[k] = v
        f.create_dataset("timestamps", data=np.arange(n, dtype=np.float64) / hz)
        for i, hand in enumerate(hands):
            key = f"robot{i}_joint_target"
            if key not in obs:
                raise SystemExit(f"{demo.name}: no {key} -- recorded before joint targets were "
                                 f"logged; re-record rather than guess the commanded action")
            q = obs[f"robot{i}_joint_pos"][()]
            g = f.create_group(hand)
            g.create_dataset("joint_position", data=q[:, :6].astype(np.float32))
            g.create_dataset("joint_velocity", data=obs[f"robot{i}_joint_vel"][()][:, :6].astype(np.float32))
            tgt = obs[key][()].copy()
            # Before the sim's first command the target buffer reads 0 (and the
            # finger target 0 = closed). The arm is holding where it stands, so
            # those leading rows are the measured position -- what the lab
            # teleop records while it holds. Reported, not silent.
            commanded = np.flatnonzero(np.any(tgt != 0, axis=1))
            k = int(commanded[0]) if commanded.size else n
            if k:
                tgt[:k] = q[:k]
                print(f"   {demo.name} {hand}: {k} leading uncommanded row(s) -> measured position")
            g.create_dataset("joint_target", data=tgt[:, :6].astype(np.float32))
            g.create_dataset("gripper_position",
                             data=np.clip(q[:, 6] / JAW_OPEN_Q, 0, 1).astype(np.float32))
            g.create_dataset("gripper_command",
                             data=np.clip(tgt[:, 6] / JAW_OPEN_Q, 0, 1).astype(np.float32))
            root = demo["states/articulation"][f"robot{i}"]["root_pose"][()]
            base_p, base_q_xyzw = root[:, :3], root[:, 3:7]
            base_wxyz = np.concatenate([base_q_xyzw[:, 3:], base_q_xyzw[:, :3]], -1)
            Rb = quat_wxyz_to_R(base_wxyz)
            Rh = quat_wxyz_to_R(obs[f"robot{i}_eef_quat"][()])
            p = obs[f"robot{i}_eef_pos"][()]
            p_b = np.einsum("nji,nj->ni", Rb, p - base_p)
            R = np.einsum("nji,njk->nik", Rb, Rh)
            tr = np.trace(R, axis1=1, axis2=2)
            qw = np.sqrt(np.clip(1 + tr, 1e-12, None)) / 2
            quat = np.stack([(R[:, 2, 1] - R[:, 1, 2]) / (4 * qw), (R[:, 0, 2] - R[:, 2, 0]) / (4 * qw),
                             (R[:, 1, 0] - R[:, 0, 1]) / (4 * qw), qw], -1)
            g.create_dataset("ee_position", data=p_b.astype(np.float32))
            g.create_dataset("ee_quaternion", data=quat.astype(np.float32))
            g.attrs["ee_note"] = "labgen grasp point (pad midpoint), robot base frame; not i2rt's ee site"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dataset", help="labgen / Isaac Lab recorder HDF5 (data/demo_k)")
    ap.add_argument("out_dir")
    ap.add_argument("--robot0-hand", default="left", choices=("left", "right"))
    ap.add_argument("--successful-only", action="store_true", default=True)
    args = ap.parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    hands = [args.robot0_hand, "right" if args.robot0_hand == "left" else "left"]
    written = 0
    with h5py.File(args.dataset, "r") as f:
        env_args = json.loads(f["data"].attrs.get("env_args", "{}"))
        sim = env_args.get("sim_args", {})
        if "dt" not in sim or "decimation" not in sim:
            raise SystemExit("dataset has no sim dt/decimation in data.attrs['env_args']; cannot know its rate")
        hz = 1.0 / (sim["dt"] * sim["decimation"])
        meta = {"labgen_dataset": str(Path(args.dataset).name)}
        if "labgen_unverified" in f.attrs:
            meta["labgen_unverified"] = f.attrs["labgen_unverified"]
        meta["labgen_note"] = "robot1 placement is a PLACEHOLDER in the sim; gripper opening from finger joints"
        for name, demo in f["data"].items():
            if args.successful_only and not bool(demo.attrs.get("success", False)):
                continue
            out = out_dir / f"{Path(args.dataset).stem}_{name}.hdf5"
            convert(demo, hz, hands, out, meta)
            written += 1
    print(f"wrote {written} demo(s) at {hz:.0f} Hz to {out_dir} (arms {hands})")
    return 0 if written else 1


if __name__ == "__main__":
    sys.exit(main())
